trigger:
 branches:
   include:
     - main
     - feature/*

pool: Infra

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job:
        displayName: InitandPlan
        steps:
          - task: TerraformTask@5
            displayName: TerraformInit
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)\environments\preprod'
              backendServiceArm: 'Infra'
              backendAzureRmResourceGroupName: 'ADO-Pipeline-Backend'
              backendAzureRmStorageAccountName: 'pipelinestorage090926'
              backendAzureRmContainerName: 'lakshmikant'
              backendAzureRmKey: 'prepod.terraform.tfstate'
          - task: TerraformTask@5
            displayName: TerrformValidate
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)\environments\preprod'
          - task: TerraformTask@5
            displayName: TerraformPlan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)\environments\preprod'
              environmentServiceNameAzureRM: 'Infra'
          
